site_name: Documentation
repo_url: ""
edit_uri: ""
#site_url: "https://test-lumi-supercomputer-docs.rahtiapp.fi/" #hasn't been chosen yet
site_description: >-
  Instructions, user guides and tutorials for the use of the LUMI supercomputer
copyright: Copyright &copy; 2021 LUMI User Support Team
nav:
  - Docs Home: 
    - Welcome: index.md
  - Computing environment:
    - Structure: overview/generic.md
    - Overview: overview/overview.md
    - Hardware:
      - CPU nodes: computing/systems/lumic.md
      - GPU nodes: computing/systems/lumig.md
      - Data analytics nodes: computing/systems/lumid.md
    - Storage:
      - Overview: storage/index.md
      - Lustre: storage/parallel/lustre.md
      - Project scratch: storage/parallel/lumip.md
      - Project fast scratch: storage/parallel/lumif.md
    - Module Environment:
      - Set module environment: computing/index.md
      - Module environment: computing/Lmod_modules.md
      - Software stacks: computing/softwarestacks.md
      - Containers: computing/containers.md
  - Connecting: 
    - Computing resources: connecting/access.md
    - SSH keys: connecting/ssh-keys.md
    - First steps in compact form: firststeps/getstarted.md
    - Additional SSH tips: connecting/connecting_.md
    - Moving data: storage/moving/scp-rsync.md
  - Running jobs:
    
      - Slurm Quickstart: computing/jobs/slurm-quickstart.md
      - Available partitions: computing/jobs/partitions.md
      - Billing: computing/jobs/billing.md
      - Batch jobs: computing/jobs/batch-job.md
      - Distribution and binding: computing/jobs/distribution-binding.md
      - High throughput: computing/jobs/throughput.md
      - Interactive usage: computing/jobs/interactive.md
    
  - Developing:
    - Overview: development/index.md
    - Compiling:
      - Programming environment: development/compiling/prgenv.md
      - Cray compilers: development/compiling/cce.md
      - GNU compilers: development/compiling/gnu.md
      - High performance libraries: development/compiling/libraries.md
      - Using hugepages: development/compiling/hugepages.md
    - Debugging:
      - Debugging: development/debugging/gdb4hpc.md
      - Memory debugging: development/debugging/valgrind4hpc.md
      - Crash or deadlock: development/debugging/stat-atp.md
    - Performance analysis:
      - Overview: development/profiling/index.md
      - CrayPat: development/profiling/perftools.md
  - Software:
    - Overview: software/index.md
    - Installing software:
      - EasyBuild: software/installing/easybuild.md
    - Containers:
      - Container Wrapper: software/containers/wrapper.md
      - MPI Container: software/containers/cray_mpich.md
      - Julia Container: software/containers/julia.md
    - Scientific Applications:
      - VASP: software/packages/vasp.md
      - Quantum ESPRESSO: software/packages/quantumespresso.md
  - Early Access Platform: eap/index.md
  - Getting Help: 
    - Help desk: generic/helpdesk.md
 
theme:
  name: material
  greetings: Welcome to the LUMI Documentation
  custom_dir: mkdocs_lumi/
  language: en
  features:
    # - navigation.instant
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - content.code.annotate
  
  palette:
    scheme: default
    primary: lumi
    accent: lumi

  font: false
  
  favicon: assets/favicon.png

  icon:
    logo: logo
  
  home_primary:
    title: Get Started
    page: firststeps/getstarted/
  home_secondary:
    title: To LUMI Main Page
    page: https://lumi-supercomputer.eu/

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Lumi-supercomputer
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/LUMIhpc

markdown_extensions:
  - toc:
      toc_depth: 3
      permalink: true
      permalink_title: Anchor link to this section for reference
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
